template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "finn1318"
__REPO__ = "lang-fin"
__UND2C__ = "fi"
__UNDEFINED__ = "Finnish"
__UND__ = "fin"
