template = "https://github.com/giellalt/template-lang-und"
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "finn1318"
__REPO__ = "lang-fin"
__UND2C__ = "fi"
__UNDEFINED__ = "Finnish"
__UND__ = "fin"
