template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "finn1318"
__REPO__ = "lang-fin"
__UND2C__ = "fi"
__UNDEFINED__ = "Finnish"
__UND__ = "fin"
