[package]
name = "fin"
human_name = "Finnish"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.fin]
filename = "fi-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-fin"
platform = "windows"
uuid = "65E51ACB-AF3D-4EE2-825C-326A58332AB6"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.fi"
package = "speller-fin"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-fin-mso"
platform = "windows"
uuid = "910AC24F-E8C9-410C-A670-CC9A641DD3C2"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-fin"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
