---
name: Docs
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v4
        with:
          repository: giellalt/giella-shared
          path: giella-shared
      - uses: actions/checkout@v4
        with:
          path: lang
      - name: Install dev dependencies
        uses: divvun/actions/lang/install-deps@master
        with:
          sudo: true
      - name: Build giella-core/giella-shared
        uses: divvun/actions/lang/build@master
        with:
          spellers: false
          fst: hfst

      # Mermaid processing starts here:
      - name: get list of files
        id: getfile
        run: |
          echo "::set-output name=files::$(find lang/docs -name '*.md' | xargs)"

      - name: print list of files for debugging
        run: |
          echo ${{ steps.getfile.outputs.files }}

      # The actual Mermaid compilation
      - name: compile mermaid
        uses: divvun/compile-mermaid-markdown-action@main
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'lang/docs/mermaid-svgs'
        env:
          HIDE_CODEBLOCKS: 1
          # The next one must be declared, with an empty value, for paths to work for us:
          ABSOLUTE_IMAGE_LINKS:
          OUTPUT_FILE_TYPE: "svg"

      - name: list generated svg fils
        run: |
          cd lang && ls -l docs/mermaid-svgs
      # Mermaid processing ends here

      - name: get frequency list
        uses: dawidd6/action-download-artifact@v8
        with:
          repo: giellalt/corpus-fin
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workflow_search: true

      - name: use frequency list
        run: |
          sudo apt-get install python3-hfst
          mkdir stats/
          python ${{ github.workspace }}/giella-core/scripts/freq-evals.py \
          -a src/fst/analyser-gt-desc.hfstol -m stats/corpus-fin.missing \
          -i ${{ github.workspace }}/corpus-fin.latest.freqs/corpus-fin.freqs \
          -n stats/corpus-fin.sus -o stats/corpus-fin.log \
          -X stats/corpus-fin.stats
          head stats/corpus-fin.missing
      - name: upload missing list
        uses: actions/upload-artifact@v4
        with: 
          name: corpus-fin.missing
          path: stats/corpus-fin.missing
      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lang/docs/
          enable_jekyll: true
